{% set version = "0.2.1" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-rlang
  version: {{ version|replace("-", "_") }}

source:
  fn: rlang_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/rlang_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/rlang/rlang_{{ version }}.tar.gz
  sha256: f2ba4826bc376e6893d1d547b97b5df7367c08b4814e73c96416c5ecb7310f3e

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - posix                # [win]
    - {{ compiler('c') }}        # [unix]
    - {{ compiler('m2w64_c') }}  # [win]
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('rlang')"  # [not win]
    - "\"%R%\" -e \"library('rlang')\""  # [win]

about:
  home: http://rlang.tidyverse.org
  dev_url: https://github.com/tidyverse/rlang
  license: GPL-3
  summary: A toolbox for working with base types, core R features like the condition system,
    and core 'Tidyverse' features like tidy evaluation.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - cbrueffer
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
